[package]
name = "rust_kafka"
version = "0.1.0"
edition = "2021"

[dependencies]
kafka = "0.10.0"
tracing-subscriber = "0.3.19"

[[bin]]
name = "producer"
path = "src/producer.rs"

[[bin]]
name = "consumer"
path = "src/consumer.rs"
